"""initial

Revision ID: 62105fe46677
Revises: 
Create Date: 2025-11-15 17:05:47.325736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62105fe46677'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'name', new_column_name='username', )
    op.alter_column('sessions', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
                postgresql_using='date::date')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.alter_column('sessions', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###
