"""Change session_player score to float

Revision ID: 62fc90dfece0
Revises: 06e9ded9d541
Create Date: 2026-09-10 07:30:48.494678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fc90dfece0'
down_revision: Union[str, Sequence[str], None] = '06e9ded9d541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_player', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    has_fractions = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM session_player WHERE score <> round(score))"
    )).scalar()
    if has_fractions:
        raise RuntimeError("Fractional scores present; downgrade would lose data.")

    op.alter_column('session_player', 'score',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
